name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
          - 22
          - 20
        react-version:
          - ^19
          - ^18
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup React ${{ matrix.react-version }}
        uses: kirkeaton/setup-react@bf49b8ed7f2eabc7b475f04076c6fb7de9280e5b # v2.0.17
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
          react-types-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 26 }}
        name: Check formatting
        run: npm run lint
      - name: Build
        run: npm run build
      - if: ${{ matrix.node-version == 26 }}
        name: Check types
        run: npm run typecheck
      - if: ${{ matrix.node-version == 26 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@7d016f859ab1635756d4f4e2e653cf9a72af4a6f # v2.0.20
