name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
        react-version:
          - ^19
          - ^18
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Setup React ${{ matrix.react-version }}
        uses: kirkeaton/setup-react@f44b147594605c7d3651a757a6292136c010647e # v1.0.5
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
          react-types-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: pnpm install
      - if: ${{ matrix.node-version == 24 }}
        name: Check formatting
        run: pnpm prettier --check "*.{cjs,json,md,ts,tsx}"
      - name: Build
        run: pnpm build
      - if: ${{ matrix.node-version == 24 }}
        name: Check types
        run: pnpm tsc --noEmit
      - if: ${{ matrix.node-version == 24 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@cce8f8a434958047a7afb9ec1029c6b28e26a55e # v1.0.13
