name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
          - 22
          - 20
        react-version:
          - ^19
          - ^18
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup React ${{ matrix.react-version }}
        uses: kirkeaton/setup-react@b1eb5c9902da368de7ca92cc4576ae12194d74fc # v2.1.4
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
          react-types-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 26 }}
        name: Check formatting
        run: npm run lint
      - name: Build
        run: npm run build
      - if: ${{ matrix.node-version == 26 }}
        name: Check types
        run: npm run typecheck
      - if: ${{ matrix.node-version == 26 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@f7e828c7aa3428c581fe334fc4ee2bb718ca6a98 # v2.1.4
